# Generated by Django 5.0.4 on 2024-05-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='titulo',
        ),
        migrations.AddField(
            model_name='perfume',
            name='marca',
            field=models.CharField(max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
